name: 'Patch BBR Plus for Kernel.'

runs:
  using: 'composite'
  steps:
      - name: Set BBR Plus for DEFCONFIG
        if: env.BBR_ENABLE == 'true'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel

          echo "CONFIG_TCP_CONG_BBRPLUS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_DEFAULT_BBRPLUS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_NET_SCH_DEFAULT_BBRP=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}

          if grep -q "CONFIG_DEFAULT_TCP_CONG" "./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}"; then
            sed -i 's/^CONFIG_DEFAULT_TCP_CONG="[^"]*"/CONFIG_DEFAULT_TCP_CONG="bbrplus"/' "./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}"
          fi

          if ! grep -q "CONFIG_NET_SCH_DEFAULT=y" "./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}"; then
            echo "CONFIG_NET_SCH_DEFAULT=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
          fi

      - name: Patch BBR Plus
        if: env.BBR_ENABLE == 'true'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE

          PACK_FILES(){
            temp_dir=$(mktemp -d)
            find . -name "*.rej" -exec cp --parents {} "$temp_dir" \;
            find . -name "*.rej" | sed 's/\.rej$//' | xargs -I {} test -f {} && find . -name "*.rej" | sed 's/\.rej$//' | xargs -I {} cp --parents {} "$temp_dir"
            tar -czf "rej_files_bbrplus.tar.gz" -C "$temp_dir" .
            rm -rf "$temp_dir"
            echo "[+] Packed Successfully."

            find . -type f \( -name "*.rej" -o -name "*.orig" \) -delete
            echo "[+] Removed all .rej and .orig files."
            echo "[+] =================================== "
          }

          REJ_FOUND(){
            if [[ "${{ env.BUILD_DEBUGGER }}" == "true" ]]; then
                echo "[+] Checking BBR Plus rej files..."
                mapfile -t REJ_FILES < <(find . -type f -name "*.rej")
                if [ ${#REJ_FILES[@]} -eq 0 ]; then
                    echo "[+] Your kernel have no any rej files, Skipped."
                else
                    for CAT_REJ in "${REJ_FILES[@]}"; do
                        echo "[-] Found .rej file: $CAT_REJ"
                        cat $CAT_REJ
                        echo "[+] =================================== "
                    done
                fi
            fi
          }

          if [[ "${{ env.KERNEL_VERSION }}" == "4.19" ]]; then
            git clone -b aarch64-rpm https://github.com/UJX6N/bbrplus-4.19 bbrplus --depth=1
          else
            git clone https://github.com/UJX6N/bbrplus-${{ env.KERNEL_VERSION }} bbrplus --depth=1
          fi

          cp bbrplus/convert_official_linux-${{ env.KERNEL_VERSION }}.x_src_to_bbrplus.patch device_kernel
          cd device_kernel
          patch -p1 < convert_official_linux-${{ env.KERNEL_VERSION }}.x_src_to_bbrplus.patch || true
          REJ_FOUND

          echo "Patched BBR Plus for your kernel successfully."

      - name: Upload Build Patch Rejected Files
        if: env.BUILD_DEBUGGER == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: patch_rejected_files
          path: |
            device_kernel/rej_files_bbrplus.tar.gz
